language: rust
cache: cargo
before_script: (cargo install rustfmt || true)
script:
- |
  export PATH=$PATH:~/.cargo/bin &&
  cd core &&
  cargo fmt -- --write-mode=diff &&
  cargo build &&
  cargo test
