version: '2'
services:
  core-base:
    build:
      context: .
      dockerfile: core/Dockerfile
    image: potboiler/core:latest
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432
  postgres-base:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  kv-base:
    build:
      context: .
      dockerfile: kv/Dockerfile
    image: potboiler/kv:latest
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432
      - SERVER_URL=http://core:8000/log
  kv-browser-base:
    build: kv-browser
    image: potboiler/kv-browser:latest
    volumes:
      - ./kv-browser/:/code
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432s
