[package]
name = "potboiler"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[build-dependencies]
serde_codegen = "*"

[[bin]]
name = "core"

[dependencies]
hybrid-clocks = {version = "*", features = ["serde"]}
uuid = {version = "*", features=["v4","serde"]}
log = "*"
log4rs = {version = ">= 0.4", features=["yaml_format"]}

iron = "*"
plugin = "*"
router = "0.2"
logger = "*"
serde = "*"
serde_json = "*"
urlencoded = "*"

potboiler_common = { path = "../potboiler_common" }

url = "*"
postgres = {version="0.11", features=["uuid","serde_json"]}
schemamama = "0.2"
schemamama_postgres = "*"

r2d2 = "*"
r2d2_postgres = "0.10"
persistent = "= 0.2.0"

hyper = "*"
resolve = "0.1.2"
