[package]
name = "potboiler"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]
build = "../build.rs"

[build-dependencies]
serde_codegen = "0.7"

[dependencies]
hybrid-clocks = {version = "*", features = ["serde"]}
uuid = {version = "0.2.3", features=["v4","serde"]}
log = "*"
log4rs = {version = ">= 0.4", features=["yaml"]}

iron = "*"
router = "*"
logger = "*"
serde = "0.7"
serde_json = "0.7"

potboiler_common = { path = "../potboiler_common" }

url = "*"
postgres = {version="*", features=["uuid","serde_json"]}
schemamama = "*"
schemamama_postgres = "*"

r2d2 = "*"
r2d2_postgres = "*"
persistent = "*"

hyper = "*"
