[package]
name = "kv"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]
build = "../build.rs"

[build-dependencies]
serde_codegen = ">=0.8"

[[bin]]
name = "kv"

[dependencies]
iron = "*"
router = "0.2.0"
logger = "*"
serde = ">=0.8"
serde_json = ">=0.8"
hybrid-clocks = {version=">=0.3.2", features = ["serde"]}

url = "*"
postgres = {version="*", features=["uuid","serde_json"]}
schemamama = "*"
schemamama_postgres = "*"

potboiler_common = { path = "../potboiler_common" }

r2d2 = "*"
r2d2_postgres = "*"
persistent = "*"

log = "*"
log4rs = {version = ">= 0.4", features=["yaml_format"]}

hyper = "*"

lazy_static = "0.1.*"
