[package]
name = "potboiler_common"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[dependencies]
iron = "*"
uuid = {version = "*", features=["use_std","v4"]}
r2d2 = "*"
r2d2_postgres = "0.10"
postgres = "0.11.11"
serde_json = "*"
log = "*"

[lib]
name = "potboiler_common"
